name: Nur UI CI/CD Pipeline

on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops

jobs:
  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      # Replace with your actual test command if you add test framework (e.g. jest)
      - name: Run tests
        run: echo "No tests yet" && exit 0

  build:
    name: 🛠️ Build Project
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next/

  deploy:
    name: 🚀 Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    #   - name: Install Vercel CLI
    #     run: npm install -g vercel

    #   - name: Deploy to Vercel
    #     run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
